configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/kernel%2Fkernel-b91d95f8e40f28d0e455d749b86c4d864ac15a264dcc2c5b317f626ff605ce2c.yml
openapi_spec_hash: befc3a683593ad7d832cfa9f0db941aa
config_hash: c6bab7ac8da570a5abbcfb19db119b6b
